name: whisper-diarization
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.13
  - numpy>=2.0.2
  - pandas>=2.2.3
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pip
  - pip:
      - openai-whisper>=20231117
      - torch>=2.0.0
      - torchaudio>=2.0.0
      - transformers>=4.48.0
      - datasets>=2.14.0
      - accelerate>=0.20.0
      - pyannote-audio>=3.3.2
      - pyannote-core>=5.0.0
      - torch-audiomentations>=0.11.0
      - soundfile>=0.12.0
      - resampy>=0.4.0
      - librosa>=0.10.0
      - wget
      - nemo_toolkit[asr]==2.0.0rc0
      - nltk
      - faster-whisper>=1.1.0
      - huggingface_hub<0.20.0
      - git+https://github.com/MahmoudAshraf97/demucs.git
      - git+https://github.com/oliverguhr/deepmultilingualpunctuation.git
      - git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git 