name: whisper-diarization  
channels:  
  - pytorch  
  - nvidia    
  - conda-forge  
  - defaults  
  
dependencies:  
  - python=3.10  
  - ffmpeg  
  - cython  
  - pytorch  
  - torchaudio  
  - pytorch-cuda=11.8  
  - numpy>=2.0.2
  - pandas>=2.2.3
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pip  
  - pip:  
    # 基础依赖
    - pika==1.3.2
    - requests==2.32.4
    - python-dotenv==1.0.0
    - psutil==5.9.8
    - loguru==0.7.2
    
    # 音频处理依赖
    - librosa>=0.10.0
    - soundfile>=0.12.0
    - resampy>=0.4.0
    
    # Whisper 相关
    - openai-whisper>=20231117
    - faster-whisper>=1.1.0
    - ctranslate2>=4.6.0
    
    # Transformers 生态
    - transformers>=4.48.0
    - datasets>=2.14.0
    - accelerate>=0.20.0
    - huggingface_hub>=0.20.0
    
    # 说话人分离相关
    - pyannote-audio>=3.3.2
    - pyannote-core>=5.0.0
    - torch-audiomentations>=0.11.0
    
    # NeMo 工具包
    - nemo_toolkit[asr]>=1.20.0
    
    # 其他工具
    - sentencepiece
    - omegaconf
    - wget
    - nltk
    
    # GitHub 依赖（需要手动安装）
    # - git+https://github.com/MahmoudAshraf97/demucs.git
    # - git+https://github.com/oliverguhr/deepmultilingualpunctuation.git
    # - git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git