name: whisper-diarization  
channels:  
  - pytorch  
  - nvidia  
  - conda-forge  
  - defaults  
  
dependencies:  
  # Python版本  
  - python>=3.10  
    
  # 系统依赖  
  - ffmpeg  
  - cython  
    
  # PyTorch生态系统  
  - pytorch  
  - torchaudio  
  - pytorch-cuda=11.8  # 或者根据你的CUDA版本调整  
    
  # 通过pip安装的包  
  - pip  
  - pip:  
    # 核心依赖  
    - faster-whisper>=1.1.0  
    - ctranslate2==4.4.0  
    - "nemo-toolkit[asr]>=2.dev"  
      
    # Git依赖包  
    - git+https://github.com/MahmoudAshraf97/demucs.git  
    - git+https://github.com/oliverguhr/deepmultilingualpunctuation.git  
    - git+https://github.com/MahmoudAshraf97/ctc-forced-aligner.git  
      
    # 其他Python依赖  
    - omegaconf  
    - wget  
    - nltk  
    - torch  
    - torchaudio  
    - logging  
    - argparse  
    - json  
    - shutil  
    - os  
    - re