name: whisper-diarization  
channels:  
  - pytorch  
  - nvidia  
  - conda-forge  
  - defaults  
  
dependencies:  
  - python>=3.10  
  - ffmpeg  
  - cython  
  - pytorch  
  - torchaudio  
  - pytorch-cuda=11.8  
  - pip  
  - pip:  
    # 使用可用的ctranslate2版本  
    - faster-whisper>=1.1.0  
    - ctranslate2==4.6.0  # 更新到可用版本  
    - sentencepiece==0.1.99  
    - omegaconf  
    - wget  
    - nltk  
    # 暂时跳过Git依赖的包