name: whisper-diarization  
channels:  
  - pytorch  
  - nvidia    
  - conda-forge  
  - defaults  
  
dependencies:  
  - python=3.10  
  - ffmpeg  
  - cython  
  - pytorch  
  - torchaudio  
  - torchvision
  - pytorch-cuda=12.1
  - numpy>=2.0.2
  - pandas>=2.2.3
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pip  
  - pip:  
    # 安装其他 Python 包
    - -r requirements.txt