name: whisper-diarization  
channels:  
  - pytorch  
  - nvidia  
  - conda-forge  
  - defaults  
  
dependencies:  
  - python>=3.10  
  - ffmpeg  
  - cython  
  - pytorch  
  - torchaudio  
  - pytorch-cuda=11.8  
  - pip  
  - pip:  
    # 核心依赖  
    - faster-whisper>=1.1.0  
    - ctranslate2==4.4.0  
    - sentencepiece==0.1.99  
    - omegaconf  
    - wget  
    - nltk  