version: '3.8'

services:
  clear_node:
    build: .
    container_name: clear_node
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST:-/}
      - QUEUE_NAME=${QUEUE_NAME:-voice_clear_queue}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8787}
      - API_UPLOAD_ENDPOINT=${API_UPLOAD_ENDPOINT:-/queue/upload}
      - API_CALLBACK_ENDPOINT=${API_CALLBACK_ENDPOINT:-/queue/callback}
      - WORK_DIR=/app/work
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CLEAR_MODEL=${CLEAR_MODEL:-FRCRN_SE_16K}
      - CLEAR_TASK=${CLEAR_TASK:-speech_enhancement}
      - OUTPUT_FORMAT=${OUTPUT_FORMAT:-wav}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}
      - CLEARVOICE_PATH=/app/ClearerVoice-Studio/clearvoice
    volumes:
      - ./work:/app/work
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./ClearerVoice-Studio:/app/ClearerVoice-Studio
    networks:
      - aivoice_network
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: clear_node_rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - aivoice_network

volumes:
  rabbitmq_data:

networks:
  aivoice_network:
    driver: bridge