name: ClearerVoice-Studio  
channels:  
  - pytorch  
  - nvidia  
  - conda-forge  
  - defaults  
dependencies:  
  - python=3.9  
  - pytorch  
  - torchvision  
  - torchaudio  
  - pytorch-cuda=11.8  
  - numpy  
  - scipy  
  - librosa   
  - pyworld  
  - opencv  
  - ffmpeg  
  - pip  
  - pip:  
    - soundfile==0.12.1
    - pesq==0.0.4  
    - pystoi==0.3.3  
    - yamlargparse==1.31.1  
    - torchinfo==1.8.0  
    - tqdm  
    - pyyaml  
    - pysptk  
    - pymcd  
    - fastdtw  
    - museval  
    - resampy  
    - onnxruntime  
    - gammatone  
    - mir_eval  
    - tensorboard  
    - torch-complex  
    - rotary-embedding-torch  
    - python_speech_features  
    - typeguard  
    - scenedetect  
    - huggingface-hub  
    - gdown  
    - pydub
